CREATE SEQUENCE SEQ_CIDADE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_TELEFONE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ENDERECO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLANO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ASSINATURA START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_CURSO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_MODULO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AULA START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_MATRICULA START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AVALIACAO START WITH 1 INCREMENT BY 1;